FROM openresty/openresty:1.21.4.1-0-focal

COPY ./docker/nginx-k8s.conf /usr/local/openresty/nginx/conf/nginx.conf

RUN rm /etc/nginx/conf.d/default.conf && \
    rm -rf /usr/local/openresty/nginx/html/* && \
    /usr/local/openresty/luajit/bin/luarocks install lua-resty-http

COPY ./lua/ /usr/local/openresty/nginx/
COPY ./docker/gateway.conf /etc/nginx/conf.d/gateway.conf
COPY ./docker/cors.conf /etc/nginx/conf.d/cors.conf
